# Generated by Django 6.0.1 on 2026-01-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=70)),
                ('limite', models.FloatField()),
                ('fechamento', models.IntegerField()),
                ('vencimento', models.IntegerField(default=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('ano', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cartao')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.competencia')),
            ],
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.fatura'),
        ),
    ]
