# Generated by Django 6.0.1 on 2026-01-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_cartao_competencia_fatura_lancamento_fatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'verbose_name_plural': 'Cartoes'},
        ),
    ]
