# Generated by Django 6.0.1 on 2026-01-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_cartao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'ordering': ['ano', 'mes']},
        ),
        migrations.RenameField(
            model_name='fatura',
            old_name='cartao_id',
            new_name='cartao',
        ),
        migrations.AlterField(
            model_name='cartao',
            name='dt_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='dt_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='vencimento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='dt_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='dt_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='competencia',
            unique_together={('mes', 'ano')},
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.UniqueConstraint(fields=('cartao', 'competencia'), name='unique_fatura_cartao_competencia'),
        ),
    ]
