# # Generated by Django 6.0.1 on 2026-01-09 18:24

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('contas', '0004_alter_competencia_options_and_more'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='competencia',
#             name='ano',
#             field=models.PositiveSmallIntegerField(),
#         ),
#         migrations.AlterField(
#             model_name='competencia',
#             name='mes',
#             field=models.PositiveSmallIntegerField(),
#         ),
#     ]
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0004_alter_competencia_options_and_more"),
    ]

    operations = []
