# Generated by Django 6.0.1 on 2026-01-09 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_competencia_ano_alter_competencia_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.fatura'),
        ),
    ]
