# Generated by Django 6.0.1 on 2026-01-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_lancamento_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='natureza',
            field=models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], default='DESPESA', max_length=10),
        ),
    ]
