# Generated by Django 6.0.1 on 2026-01-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_lancamento_natureza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['data']},
        ),
    ]
