# Generated by Django 6.0.1 on 2026-01-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_alter_lancamento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_pago',
            field=models.FloatField(null=True),
        ),
    ]
