# Generated by Django 6.0.1 on 2026-01-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_fatura_data_pagamento_fatura_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
