# Generated by Django 6.0.1 on 2026-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0010_alter_lancamento_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
