# Generated by Django 6.0.1 on 2026-01-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_alter_fatura_valor_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='eh_rotativo',
            field=models.BooleanField(default=False),
        ),
    ]
