# Generated by Django 6.0.1 on 2026-02-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_lancamento_eh_rotativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='fixo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='parcelas',
            field=models.IntegerField(default=False),
        ),
    ]
