# Generated by Django 6.0.1 on 2026-02-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_lancamento_fixo_lancamento_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='fixo',
            field=models.CharField(choices=[('NAO', 'Nao'), ('FIXO', 'Fixo'), ('PARCELADO', 'Parcelado')], default='NAO', max_length=10),
        ),
    ]
