# Generated by Django 6.0.1 on 2026-02-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0014_alter_lancamento_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='is_pagamento_fatura',
            field=models.BooleanField(default=False),
        ),
    ]
