# Generated by Django 6.0.1 on 2026-03-21 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0015_lancamento_is_pagamento_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='grupo_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
